---
# enable zabbix repo
- name: enable zabbix repository
  yum:
    name: https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-1.el7.noarch.rpm
    state: present

#  install packages
- name: Install zabbix agent package
  yum:
    name: zabbix-agent

- name: Create config file for zabbix-agent
  template: 
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: h_zabbix-agent_restart

- name: enable zabbix-agent service at boot
  service:
    name: zabbix-agent
    enabled: yes
    state: started